### ISSUE TITLE
I need your help to run this bot.

### ISSUE THREAD

**Issue by propoka** [chatrsc07/Discord-chat-bot#1]
Dear chatRSC,

I really appreciate your efforts in developing this code. However, I encountered some problems during the bot's trial run. I would really appreciate your assistance. Thank you.

I am running the bot on the sparkedhost.us server and I am getting an error as shown in the image. I am not good at coding so I would once again appreciate your support.

Best regards.

![Screenshot 2023-10-20 153907](https://github.com/chatrsc07/Discord-chat-bot/assets/88265464/a41e796b-60cc-4842-94bf-419a1013dbed)

![Screenshot 2023-10-20 153352](https://github.com/chatrsc07/Discord-chat-bot/assets/88265464/5b777f39-858a-41eb-8bae-a95b3a739557)

`customer@apollopanel~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[Pterodactyl Daemon]: Executing cautionary malware scan...
customer@apollopanel~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
Python3 version: 3.9.18
customer@apollopanel~ Server marked as running...
PIP3 version: 23.3
Git version: 2.30.2
customer@sparkedhost:~# if [[ -d .git ]]; then git pull; fi; if [[ ! -z ${PY_PACKAGES} ]]; then pip3 install -U --prefix .local ${PY_PACKAGES}; fi; if [[ -f /home/container/requirements.txt ]]; then pip3 install -U --prefix .local -r requirements.txt; fi; python3 /home/container/${STARTUP_FILE}
Collecting discord.py
  Downloading discord.py-2.3.2-py3-none-any.whl.metadata (4.9 kB)
Collecting aiohttp<4,>=3.7.4 (from discord.py)
  Downloading aiohttp-3.8.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 3.2 MB/s eta 0:00:00
Collecting charset-normalizer<4.0,>=2.0 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading charset_normalizer-3.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (32 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 8.3 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading yarl-1.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (269 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.4/269.4 kB 11.2 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading frozenlist-1.4.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4,>=3.7.4->discord.py)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<4,>=3.7.4->discord.py)
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 495.1 kB/s eta 0:00:00
Downloading discord.py-2.3.2-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 40.8 MB/s eta 0:00:00
Downloading aiohttp-3.8.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 21.9 MB/s eta 0:00:00
Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Downloading charset_normalizer-3.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 kB 8.2 MB/s eta 0:00:00
Downloading frozenlist-1.4.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (228 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 15.5 MB/s eta 0:00:00
Installing collected packages: multidict, idna, frozenlist, charset-normalizer, attrs, async-timeout, yarl, aiosignal, aiohttp, discord.py
Successfully installed aiohttp-3.8.6 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 charset-normalizer-3.3.0 discord.py-2.3.2 frozenlist-1.4.0 idna-3.4 multidict-6.0.4 yarl-1.9.2
Traceback (most recent call last):
  File "/home/container/main.py", line 1, in <module>
    import bot
  File "/home/container/bot.py", line 4, in <module>
    import responces  # Assuming you have this module for responses
  File "/home/container/responces.py", line 5, in <module>
    from bardapi import Bard
ModuleNotFoundError: No module named 'bardapi'
customer@apollopanel~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[Pterodactyl Daemon]: Executing cautionary malware scan...
customer@apollopanel~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
Python3 version: 3.9.18
customer@apollopanel~ Server marked as running...`

**Comment by chatrsc07** [comment]
Hey, I'm still new to this field and this is my first project using the bardapi and discord. It seems that you didn't install the bardapi through pip. Could you try pip installing bardapi? also btw you should not give out the tokens as they are unique to each person. I suggest you make a new token for your bot through the discord developer portal.
